config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get   '/discover', to: 'books#index'
  resources :books

  resources :clubs, only: [:show, :create, :new] do
    resources :users, only: [:index], controller: 'club_users'
    resources :comments, only: [:index], controller: 'club_comments'
  end

  resources :comments, only: [:create]

  get '/dashboard', to: 'users#show'

  get   '/register', to: 'users#new'
  post  '/register', to: 'users#create'

  get   '/login', to: 'sessions#new'
  post  '/login', to: 'sessions#create'
  get   '/logout', to: 'sessions#destroy'

  get   '/auth/google_oauth2/callback', to: 'users#create'

  get '/dashboard', to: 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id]
      UserFacade.find_user(session[:user_id])
    end
  end

  def quote
  #   @quote = QuoteFacade.get_quote
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:search].present? && BookFacade.find_book(params[:search]).nil?
      flash[:error] = "We failed you or this book does not exist"

    elsif params[:search].present?
      @books = BookFacade.find_book(params[:search])
      #need a way to refresh page as flash error is persisting through.
    end
  end

  def show
    @book = BookFacade.book_show(params[:id])
  end

  private
  def book_params
    params.require(:books).permit(:title, :author, :summary, :rating, :genre)
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :quote, only: [:new]
  
  def show
    club_host = current_user
    club_id = params[:id]
    @club = ClubFacade.get_club(club_id)
    @club_users = ClubFacade.get_club_users(club_id)
    @book_id = @club.book_id
    @book = BookFacade.book_show(@book_id)
    @comments = ClubFacade.get_club_comments(club_id)
  end

  def new
    @book_id = params[:book_id]
    @users = UserFacade.all_users
  end

  def create
    if params[:user_ids].nil?
      params[:user_ids] = []
      params[:user_ids].push(current_user.id)
      @book_id = params[:book_id]
      @club = ClubFacade.create_club(name: params[:name], book_id: params[:book_id], host_id: current_user.id,
                                     params: params[:user_ids])
      redirect_to "/clubs/#{@club.id}"
    else
      @book_id = params[:book_id]
      params[:user_ids].push(current_user.id)
      @club = ClubFacade.create_club(name: params[:name], book_id: params[:book_id], host_id: current_user.id,
                                     params: params[:user_ids])
      redirect_to "/clubs/#{@club.id}"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
     comment = CommentFacade.post_comment(title: params[:title], body: params[:body], user_id: current_user.id, club_id: params[:club_id])
     redirect_to "/clubs/#{params[:club_id]}"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :quote, only: [:new]

  def new; end

  def destroy
    session.destroy
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :quote, only: [:new]

  def new; end

  def show
    unless current_user.nil?
      @user = current_user
      @clubs = UserFacade.user_clubs(@user.id)
    end
  end

  def create
    # conn = Faraday.new(url: 'http://localhost:3000/')
    conn = Faraday.new(url: 'https://hidden-garden-03870.herokuapp.com/')
    auth_hash = request.env['omniauth.auth']
    email = auth_hash['info']['email']

    response = conn.post('/api/v1/users') do |req|
      req.headers['Content-Type'] = 'application/json'
      req.body = JSON.generate(user: { username: email, email: email })
    end

    if response.status == 400
      response = conn.get('/api/v1/users') do |req|
        req.headers['Content-Type'] = 'application/json'
        req.body = JSON.generate(user: { username: email, email: email })
      end
      user = JSON.parse(response.body, symbolize_names: true)[:data]
      selected = user.select {|selected_user| selected_user[:attributes][:email] == email}
      session[:user_id] = selected[0][:id]
    else
      user = JSON.parse(response.body, symbolize_names: true)[:data]
      session[:user_id] = user[:id]
    end
    redirect_to '/dashboard'

    # if response.status == 400
    #   response = conn.get('/api/v1/users') do |req|
    #     req.headers['Content-Type'] = 'application/json'
    #     req.body = JSON.generate(user: { username: email, email: email })
    #   end
    # end
    # user = JSON.parse(response.body, symbolize_names: true)[:data]
    # # binding.pry
    # session[:user_id] = user[:id]
    # redirect_to '/dashboard'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # before_action :quote, only: [:index]

  def index
    @book_of_the_week = BookFacade.book_show("aWYwDwAAQBAJ")
    @popular_books = NytFacade.best_sellers_hardcover_fiction

    if params[:search].present? && BookFacade.find_book(params[:search]).nil?
      flash[:error] = "We failed you or this book does not exist"

    elsif params[:search].present?
      @books = BookFacade.find_book(params[:search])
      #need a way to refresh page as flash error is persisting through.
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/show.html.erb
<head>
  <style>
    .cover-img {
      display: block;
      margin-left: auto;
      margin-right: auto;
      width: 90%;
      height: auto;
      border-radius: 10px;
    }

    .centered {
      text-align: center;
    }
  </style>
</head>

<body>
  <div class="container">
    <div class="row">
      <!-- book cover, title, and create club link -->
      <div class="col">
        <div class="container centered">

          <div class="row">
            <img id="book-cover" class="cover-img" alt="book cover" src= <%= @book.larger_image %>>
          </div><br><br>

          <div id="create-club-button" class="row">
            <% if session[:user_id] %>
              <div class="button">
                <button type="button" class="btn btn-secondary btn-lg"><%= button_to "Create Book Club", "/clubs/new", params: {book_id: @book.id} , method: :get %></button>

              </div>
            <% else %>
              <div class="container">
                <p>To start a club with this book, please <%= link_to 'Login', '/login' %>.</p>
              </div>
            <% end %>
          </div><br>
        </div>
      </div>


      <!-- book information -->
      <div class="col">
        <div class="container">
          <div class="row">
            <h3>Title: <%= @book.title %> </h3>
          </div><br>

          <div class="row">
            <h3>Author(s):</h3>
          </div>

          <div class="row">
            <p><% @book.author.each do |author| %>
              <%= author %>
              <% end %>, </p>
          </div><br>

          <div class="row">
            <% if @book.summary == nil %>
             <h3> Summary: </h3> <p>n/a</p>
            <% else %>
            <h3>Summary: </h3>

            <span> <%= sanitize @book.summary %></span>
            <% end %>
          </div><br>

          <div class="row">
            <% if @book.rating == nil%>
             <h3>Rating: </h3> <p>n/a</p>
            <% else %>
            <h3>Book rating: </h3> <p><%= @book.rating %></p>
            <% end %>
          </div><br>

          <div class="row">
            <% if @book.genre == nil%>
                <h3> Genre(s): </h3> <p>n/a</p>
            <% else %>
            <h3>Genre(s): </h3><p><% @book.genre.each do |genre| %>
              <%= genre %>
              <% end %>
            <% end %> </p>
          </div><br>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/clubs/new.html.erb
<head>
  <style>

  </style>
</head>

<body>
  <%= render partial: '/layouts/partials/random_quote' %>
  
  <div class="container">
    <div class="container text-center" text-align="center">
      <h1>Create Club</h1>
    </div><br>

    <div id="form" class="container">
      <%= form_with url: "/clubs",  method: :post, local: true do |f| %>
      <%= f.hidden_field :book_id, value: @book_id %>
      <%= f.hidden_field :host_id, value: session[:id] %>

      <div class="row">
        <div class="col">
          <div class="container">
            <%= f.label :name, 'Club Name' %>
            <%= f.text_field :name, required: true %><br><br><br>

            <button type="button" class="btn btn-secondary btn-lg"><%= f.submit "Create Book Club" %></button>
          </div>
        </div>

        <div class="col">
          <div class="container">
            <p>Invite Users? (*not required)</p>

            <% user_counter = 0 %>
            <% @users.each do |user| %>
              <div id="select-user-<%= user_counter %>">
                <% if user.id != current_user.id %>
                <p><%= check_box_tag('user_ids[]', user.id, nil, :id => user.username) %>
                   <%= f.label "#{user.username}" %></p>
                <% end  %>
              </div>
              <% user_counter += 1 %>
            <% end  %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>





</body>

app/views/clubs/show.html.erb
<head>
  <style>

    .book-img {
      width: 80%;
      height: auto;
      border-radius: 10px;
    }

    .comment-container {
      background-color: white;
      padding: 5px;
      border-left: 3px solid darkgray;
      border-bottom: 3px solid whitesmoke;
      border-radius: 5px;
    }

  </style>
</head>

<body>
  <div class="container">
    <div class="row">
      <!-- book club information -->
      <div class="col">
        <div class="container">
          <div class="row">
            <div class="col">
              <h1>Club: <%= @club.name %> </h1>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <h6>Club Book: <%= @book.title %> </h6>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <img class="book-img" src= <%= @book.image %> >
            </div>
          </div>
        </div><br>

        <div class="container">
          <div class="row">
            <div class="col">
              <h1>Members:</h1>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <ul>
              <% @club_users.each do |user| %>
                <% if user.id == @club.host_id.to_s %>
                <li><%= user.username %> (Host) - <%= user.email %> </li>
                <% else %>
                <li> <%= user.username %> - <%= user.email %></li>
                <% end %>
              <% end %>
              <ul>
            </div>
          </div>
        </div>

      </div>

      <!-- discussion section -->
      <div class="col">
        <div class="container">

          <div class="row">
            <div class="col">
              <h2>Discussion:</h2>
            </div>
          </div>

          <!-- make a comment -->
          <div class="row">
            <div id="comment-add">
              <h4>Add a Comment...</h4>
              <%= form_with url: '/comments', method: :post, local: true do |f| %>

              <%= f.text_field :title, required: :true, placeholder: 'Comment Title' %><br><br>

              <%= f.text_area :body, required: true, placeholder: 'Your message here' %><br

              <%= f.hidden_field :user_id, value: current_user.id %>

              <%= f.hidden_field :club_id, value: @club.id %>

              <%= f.submit 'Submit', method: :post %><br><br>
              <% end %>
            </div>
          </div>

          <!-- all comments -->
          <div class="row">
            <div class="col">
              <% @comments.each do |comment| %>
                <% @club_users.each do |user| %>
                  <% if comment.user_id == user.id.to_i %>
                  <p> <img src="<%= asset_path 'profile_pic_2.png' %>" width="20" height="20" class="rounded-circle">  <%= user.username %> </p>
                  <div class="comment-container">
                  <p><b> <%= comment.title %></b><br>
                <%= comment.body %></p>
              </div><br>
                  <% end  %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>BookClubFe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <style media="screen">
      body {
        background-color: whitesmoke;
      }

      .container {
        background-color: white;
        padding: 15px;
        border-radius: 15px;
        border: 3px solid whitesmoke;
      }
    </style>
  </head>

  <body>
    <!-- Navbar -->
    <nav>
      <%= render partial: '/layouts/partials/logo_nav_profile' %>
    </nav><br>

    <%= yield %>
  </body>
</html>

app/views/layouts/partials/_logo_nav_profile.html.erb
<style media="screen">
  .left-margin {
    margin-left: 10px;
  }

  .right-margin {
    margin-right: 10px;
  }
</style>

<div id="nav-bar" class="container">
  <div id="logo-nav-profile">
    <nav class="navbar navbar-dark bg-secondary navbar-expand-sm">

      <!-- logo is a link -->
      <a class="navbar-brand" href="/">
        <img id="logo" src="<%= asset_path 'logo.png' %>" class="left-margin" width="80" height="80" alt="logo">
      </a>

      <!-- user profile image is dropdown menu -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse flex-row-reverse right-margin" id="navbar-list-4">
        <ul class="navbar-nav">

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" >
                <img src="<%= asset_path 'profile_pic_2.png' %>" width="40" height="40" class="rounded-circle">
              </a>

              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <% if session[:user_id] %>
                  <a class="dropdown-item" href="/dashboard">Dashboard</a>
                  <a class="dropdown-item" href="#">Edit Profile</a>
                  <a class="dropdown-item" href="/logout">Logout</a>
                <% else %>
                  <a class="dropdown-item" href="/register">Register</a>
                  <a class="dropdown-item" href="/login">Login</a>
                <% end %>
              </div>
            </li>
        </ul>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/partials/_random_quote.html.erb
<head>
  <style media="screen">
    #random-quote {
      position: relative;
      text-align: center;
    }
  </style>
</head>

<% if @quote %>
  <div id="random-quote" class="container">
    <p> <%= @quote.quote %> <br> - <%= @quote.author %></p>
  </div><br>
<% else %>
  <div class="container">
    <div id="static-quote">
      <p>"You will be the same person in five years as you are today except for the people you meet and the books you read." <br>

        - Charlie "Tremendous Jones"
      </p>
    </div>
  </div><br>
<% end %>

app/views/layouts/partials/_render_flash.html.erb
<% flash.each do |type, notice| %>
    <div class="alert alert-info">
      <p><%= notice %></p>
    </div>
<% end %>

app/views/users/new.html.erb
<header>
  <style>
    .container {
      text-align: center;
      justify-content: center;
    }
  </style>
</header>

<body>
  <%= render partial: '/layouts/partials/random_quote' %>

  <% if session[:user_id] %>
    <div class="container">
      <div id="logged-in-user-message">
        <p text-align="center">You are already logged in.</p><br>
        <p text-align="center">If you would like to register a new user, please <%= link_to "Logout", '/logout' %> first.</p>
      </div>
    </div>

  <% else %>
    <div class="container">
      <div class="form-container">
        <%= form_with url: '/register', method: :post, local: true do |f| %>

        <%= f.text_field :name, required: :true, placeholder: 'Name' %><br><br>

        <%= f.email_field :email, required: true, placeholder: 'email@domain.com' %><br><br>

        <%= f.password_field :password, required: true, placeholder: 'password' %><br><br>

        <%= f.password_field :password_confirmation, required: true, placeholder: 'confirm password' %><br><br>

        <button type="button" class="btn btn-secondary btn-lg"><%= f.submit 'Register' %></button>

        <% end %>
      </div>

      <br><br>

      <p>--- OR ---</p><br>

      <button type="button" class="btn btn-secondary btn-lg"><%= button_to 'Register with Google', '/auth/google_oauth2/', method: :get, params: {client_id: "#{ENV['GOOGLE_CLIENT_ID']}" } %></button>

    </div>
  <% end %>
</body>

app/views/users/show.html.erb
<head>
  <style>

  </style>
</head>

<body>
  <% if session[:user_id].nil? %>

    <div class="container">
      <div id="not_logged_in">
        <p text-align="center">Yo, you gotta <%= link_to 'login', '/login' %> first, dawg...</p>
      </div>
    </div>

  <% else %>
    <center><h1><%= @user.username %>'s Dashboard</h1></center>

    <div class="container">
      <div class="row">
        <!-- my book clubs -->
        <div class="col">
          <div class="container">
            <div class="row">
              <div class="col">
                <h3>My Bookclubs:</h3>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <% @clubs.each do |club| %>
                <p><%= link_to club.name, club_path(club.id) %></p>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <!-- my recent activity -->
        <div class="col">
          <div class="container">
            <div class="row">
              <div class="col">
                <h3>My Recent Activity:</h3>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <p>User's recent activity will show up here.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</body>

app/views/welcome/index.html.erb
<head>
  <style>
    #static-quote {
      position: relative;
      text-align: center;
      padding: 20px;
    }

    .cover-img {
      display: block;
      margin-left: auto;
      margin-right: auto;
      width: 90%;
      height: auto;
      border-radius: 10px;
    }

    .thumbnail-img {
      display: block;
      margin-left: auto;
      margin-right: auto;
      width: 50%;
      height: auto;
      border-radius: 10px;
    }

    /* Style the button that is used to open and close the collapsible content */
    .collapsible {
      background-color: #eee;
      color: #444;
      cursor: pointer;
      padding: 18px;
      width: 100%;
      border: none;
      text-align: left;
      outline: none;
      font-size: 15px;
    }

    /* Add a background color to the button if it is clicked on (add the .active class with JS), and when you move the mouse over it (hover) */
    .active, .collapsible:hover {
      background-color: #ccc;
    }

    /* Style the collapsible content. Note: hidden by default */
    .content {
      padding: 0 18px;
      display: none;
      overflow: hidden;
      background-color: #f1f1f1;
    }

    .popular-book-container {
      background-color: white;
      padding: 5px;
      border-bottom: 5px solid whitesmoke;
    }
  </style>
</head>

<body>
  <div class="container">
    <div id="static-quote">
      <p>"You will be the same person in five years as you are today except for the people you meet and the books you read." <br>

        - Charlie "Tremendous Jones"
      </p>
    </div>
  </div><br>

  <div class="container">
    <div class="row">
        <!-- search bar -->
        <div class="col">
          <div class="container">
              <div class="row">
                  <div class="col-md-6 col-md-offset-3">
                    <h3>Discover Books</h3>
                  </div>

                  <div class="row">
                      <div class="col">
                        <%= form_with url: '/', method: :get, local: true do |f| %>
                        <%= f.text_field :search, required: true %><br><br>
                        <%= f.submit "Search" %>
                        <% end %><br>

                        <%= render partial: '/layouts/partials/render_flash' %>
                      </div>
                  </div>

                  <div class="row">
                    <div class="col-md-8 col-md-offset-3">
                      <% if @books %>
                      <h3>Results</h3>
                        <% @books.each do |book| %>
                          <p> <%= link_to book.title, "/books/#{book.id}" %> </p>
                        <% end %>
                      <% end  %>
                    </div>
                  </div>
              </div>
          </div>
        </div>

        <!-- suggested books -->
        <div class="col">
          <!-- book of the week -->
          <div class="container">
            <div class="row">
              <h3>Book of the Week!</h3>
            </div>

            <div class="row">
              <div class="col">
                <div class="row">
                  <a href="/books/<%= @book_of_the_week.id %>">
                    <img class="cover-img" src="<%= @book_of_the_week.larger_image %>" alt="book of the week cover">
                  </a>
                </div>
              </div>

              <div class="col">
                <div class="row">
                  <p>Author: <% @book_of_the_week.author.each do |author| %>
                    <%= author %>
                    <% end %></p>
                </div>

                <div class="row">
                  <% if @book_of_the_week.genre == nil%>
                      <p> Genre(s): n/a</p>
                  <% else %>
                  <p>Genre(s): <% @book_of_the_week.genre.each do |genre| %>
                    <%= genre %>
                    <% end %>
                  <% end %> </p>
                </div>

                <div class="row">
                  <button type="button" class="collapsible">Summary</button>

                  <div class="content">
                    <p> <%= sanitize @book_of_the_week.summary %> </p>
                  </div>

                  <script>
                    var coll = document.getElementsByClassName("collapsible");
                    var i;

                    for (i = 0; i < coll.length; i++) {
                      coll[i].addEventListener("click", function() {
                        this.classList.toggle("active");
                        var content = this.nextElementSibling;
                        if (content.style.display === "block") {
                          content.style.display = "none";
                        } else {
                          content.style.display = "block";
                        }
                      });
                    }
                  </script>
                </div>
              </div>
            </div>
          </div><br>

          <!-- popular books -->
          <div class="container">
            <h3>Popular Books</h3>

            <% @popular_books.each do |book| %>
                <div class="popular-book-container">
                  <div class="col">
                    <div class="row">
                      <div class="col-md-4 col-md-offset-3">
                        <img class="thumbnail-img" src= <%= book.image %>>
                      </div>

                      <div class="col">
                        <p>Title: <%= book.title %></p>
                        <p>Author: <%= book.author %></p>
                        <p>Summary: <%= book.description %></p>
                      </div>

                    </div>
                  </div>
                </div><br>
              <% end %>
          </div><br>
        </div>
    </div>
  </div>


</body>